import { useState } from "react";
import { api } from "./api";
import { Service, Deployment, Node, phases, kinds, bytes, time } from "./types";
export function Badge({ status }: { status: string }) { return <span className={`badge badge-${status}`}><i />{phases[status] || status}</span>; }
function Chart({ service }: { service: Service }) {
  const points = service.history ?? []; const max = Math.max(1, ...points.flatMap(p => [p.rx_bytes_per_sec, p.tx_bytes_per_sec]));
  const line = (key: "rx_bytes_per_sec" | "tx_bytes_per_sec") => points.map((p, i) => `${44 + i / Math.max(1, points.length - 1) * 690},${158 - p[key] / max * 125}`).join(" ");
  return <div className="traffic-chart"><div className="chart-caption"><b>服务流量趋势</b><span><i className="rx-key" />接收 <i className="tx-key" />发送 · 约 5 秒采样 · 基础设施约 10 秒</span></div>{points.length < 2 ? <div className="chart-empty">等待两个有效采样点后显示趋势</div> : <svg viewBox="0 0 760 194" role="img" aria-label={`${service.name} 接收和发送流量趋势`}><text x="44" y="18">{bytes(max)}/s</text>{[33, 75, 117, 159].map(y => <line key={y} x1="44" x2="734" y1={y} y2={y} className="chart-grid" />)}<polyline points={line("rx_bytes_per_sec")} className="chart-rx" /><polyline points={line("tx_bytes_per_sec")} className="chart-tx" /><text x="44" y="184">{new Date(points[0].at).toLocaleTimeString()}</text><text x="734" y="184" textAnchor="end">{new Date(points[points.length - 1].at).toLocaleTimeString()}</text></svg>}</div>;
}
export default function Monitor({ services, deployments, nodes, sync, query, setQuery }: { services: Service[]; deployments: Deployment[]; nodes: Node[]; sync: string; query: string; setQuery: (q: string) => void }) {
  const [selected, setSelected] = useState(""); const [filter, setFilter] = useState("all"); const [logs, setLogs] = useState("");
  const chosen = services.find(s => s.id === selected); const attention = services.filter(s => ["degraded", "failed", "offline"].includes(s.status));
  const visible = services.filter(s => (filter === "all" || (filter === "attention" ? ["degraded", "failed", "offline"].includes(s.status) : s.kind === filter)) && `${s.name} ${s.id} ${s.node_id ?? ""} ${s.deployment_id ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const gateways = services.filter(s => s.kind === "inference-gateway");
  const getLogs = async (node: string) => { try { const result = await api<Record<string, string>>(`/v1/agents/${encodeURIComponent(node)}/logs`); setLogs(Object.entries(result).map(([k, v]) => `[${k}]\n${v}`).join("\n\n") || "还没有工作进程日志"); } catch (e) { setLogs(String(e)); } };
  return <><div className="page-heading"><div><p>OBSERVABILITY</p><h1>每个服务，都看得见</h1><span>查看运行状态、请求与流量，定位协同推理链路的问题。</span></div><small>最后同步<br />{time(sync)}</small></div>
    <div className="summary-grid"><article><span>已纳管服务</span><strong>{services.length}<small>个</small></strong><footer>{services.filter(s => s.status === "ready").length} 个正常运行</footer></article><article><span>需要关注</span><strong className={attention.length ? "warning-number" : ""}>{attention.length}<small>个</small></strong><footer>失败、降级或心跳失联</footer></article><article><span>推理入口请求速率</span><strong>{gateways.reduce((a, s) => a + s.rps, 0).toFixed(2)}<small>req/s</small></strong><footer>仅统计模型入口，避免重复计数</footer></article><article><span>就绪模型服务</span><strong>{deployments.filter(d => d.phase === "ready").length}<small>/ {deployments.length}</small></strong><footer>{nodes.length} 台已登记节点</footer></article></div>
    <section className="panel"><div className="panel-heading"><div><h2>服务总览</h2><p>点击任一服务，查看流量趋势与详细指标。</p></div><input className="search-input" aria-label="搜索服务" placeholder="搜索服务 / 节点…" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="filter-row">{[["all", "全部服务"], ["attention", "需要关注"], ["rpc-worker", "GPU 工作服务"], ["petals-worker", "Petals 模型块"], ["model-server", "模型推理"], ["agent", "节点代理"], ["infrastructure", "基础设施"]].map(([id, label]) => <button key={id} className={filter === id ? "filter-active" : ""} onClick={() => setFilter(id)}>{label}</button>)}</div><div className="service-table"><table><thead><tr><th>服务 / 所属节点</th><th>状态</th><th>请求速率</th><th>接收 / 发送</th><th>错误 / 请求</th><th>平均耗时</th><th>最近上报</th></tr></thead><tbody>{visible.map(s => <tr key={s.id} className={selected === s.id ? "service-selected" : ""}><td><button className="service-link" onClick={() => { setSelected(s.id); setLogs(""); }}><b>{s.name}</b><small>{kinds[s.kind] || s.kind} · {s.node_id || "管理节点"}</small></button></td><td><Badge status={s.status} /></td><td>{(s.http_metrics || s.kind === "petals-worker") ? s.status === "offline" ? "—" : `${s.rps.toFixed(2)} /s` : "不适用"}</td><td>{s.traffic_metrics ? s.status === "offline" ? "—" : <><span className="rx-text">↓ {bytes(s.rx_bytes_per_sec)}/s</span><small className="tx-text">↑ {bytes(s.tx_bytes_per_sec)}/s</small></> : "未采集"}</td><td>{(s.http_metrics || s.kind === "petals-worker") ? `${s.errors} / ${s.requests}` : s.kind === "rpc-worker" ? `${s.errors} 次连接错误` : "不适用"}</td><td>{(s.http_metrics || s.kind === "petals-worker") && s.requests ? `${s.average_latency_ms.toFixed(1)} ms` : "—"}</td><td className="time-cell">{time(s.last_seen)}</td></tr>)}</tbody></table>{visible.length === 0 && <div className="empty-panel">没有符合条件的服务</div>}</div><div className="panel-note">HTTP/RPC 流量为实际载荷字节；基础设施流量来自对应项目容器网卡。两者口径不同，不宜相加。RPC 按连接统计，Petals 按推理会话统计，其字节仅含序列化推理载荷；平均耗时包含完整流式响应时长。</div></section>
    {chosen && <section className="panel"><div className="panel-heading"><div><h2>{chosen.name}</h2><p>{chosen.id} · {chosen.address || "本地服务"}</p></div><button onClick={() => setSelected("")}>收起</button></div>{chosen.message && <div className="detail-message">{chosen.message}</div>}<div className="detail-metrics"><div><span>累计接收</span><b>{chosen.traffic_metrics ? bytes(chosen.rx_bytes) : "未采集"}</b></div><div><span>累计发送</span><b>{chosen.traffic_metrics ? bytes(chosen.tx_bytes) : "未采集"}</b></div><div><span>{chosen.kind === "petals-worker" ? "活动推理会话" : chosen.http_metrics ? "进行中请求" : "活动连接"}</span><b>{chosen.status === "offline" ? "—" : chosen.active}</b></div><div><span>{chosen.kind === "petals-worker" ? "累计推理会话" : chosen.http_metrics ? "当前采样错误率" : "累计连接数"}</span><b>{chosen.kind === "petals-worker" ? chosen.requests : chosen.http_metrics ? `${(chosen.error_ratio * 100).toFixed(1)}%` : chosen.connections}</b></div></div>{chosen.traffic_metrics && <Chart service={chosen} />}{chosen.engine && <div className="engine-metrics">{Object.entries(chosen.engine).map(([k, v]) => <span key={k}>{k}<b>{v.toLocaleString()}</b></span>)}</div>}{chosen.node_id && <button onClick={() => void getLogs(chosen.node_id!)}>查看节点工作进程日志</button>}{logs && <pre className="log-view">{logs}</pre>}</section>}
  </>;
}
